# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbs_user',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bbs',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
