# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180309_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_user',
            name='signature',
            field=models.CharField(default='this gus is too lazy', max_length=128),
        ),
    ]
